REACT_APP_SITE_TITLE='Parque Arauco CMS'
REACT_APP_API_URL='https://api-dev.parquearauco.cl/'
REACT_APP_DEFAULT_LOCALE='es'


PA_AWS_CREDENTIALS='s3-pa-dev-credentials'
PA_AWS_BUCKET_NAME='ecosis-dev-bucket-v2'
PA_AWS_REGION='us-east-1'
PA_AWS_STORAGE_FOLDER='cms/'
PA_BUILD_FILES='build/'
PA_CLOUDFRONT_DISTRIBUTION_ID='E2KV8LYWYVJLKE'